config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	searchkick
	validates :contact_name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if params[:search].present?
      @contacts = Contact.search(params[:search], misspellings: false) 
    else
      @contacts = []
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    redirect_to root_path
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:contact_name, :position, :affiliation, :context, :address, :email, :mobile, :landline, :fax)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-xs-12"> <%= f.input :contact_name, :label => "Name:" %> </div>
      <div class="col-xs-6"> <%= f.input :position, :label => "Position:" %> </div>
      <div class="col-xs-6"> <%= f.input :affiliation, :label => "Affiliation:" %> </div>
      <div class="col-xs-12"> <%= f.input :context, :label => "Context of Meeting" %> </div>
    </div>

    <h3><b>Contact Details:</b></h3>

    <div class="row">
      <div class="col-xs-12"> <%= f.input :address, :label => "Physical Address:" %> </div>
      <div class="col-xs-6"> <%= f.input :mobile, :label => "Mobile:" %> </div>
      <div class="col-xs-6"> <%= f.input :email, :label => "Email:" %> </div>
      <div class="col-xs-6"> <%= f.input :landline, :label => "Landline:" %> </div>
      <div class="col-xs-6"> <%= f.input :fax, :label => "Fax:" %> </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-success pull-right" %>
  </div>
<% end %>

app/views/contacts/_results.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
  <% @contacts.each do |contact| %>
  <div class="box">
    <strong>Name: </strong> <%= contact.contact_name %><br>
    <strong>Position: </strong> <%= contact.position %><br>
    <strong>Affiliation: </strong> <%= contact.affiliation %><br>
    <strong>Context of Meeting: </strong> <%= contact.context %><br>
    <br>
    <strong><u>Contact Info:</u></strong><br>
    <strong>Address: </strong> <%= contact.address %><br>
    <strong>Email: </strong> <%= contact.email %><br>
    <strong>Mobile: </strong> <%= contact.mobile %><br>
    <strong>Landline: </strong> <%= contact.landline %><br>
    <strong>Fax: </strong> <%= contact.fax %><br>
    <div class="pull-right"><%= link_to 'Edit', edit_contact_path(contact) %> | <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></div>
  </div>
  <% end %>
</div>

app/views/contacts/_search.html.erb
<!-- contains search field -->

<%= form_tag contacts_path, method: :get, role: "search" do %>
<div class="row">
	<div class="col-xs-12">
		<div class="input-group input-group-lg">
	    	<%= text_field_tag :search, params[:search], :placeholder => "Search", class: "form-control" %>
	    	<div class="input-group-btn">
	    		<%= button_tag(type: "submit", class: "btn btn-info") do %>
				    <i class="fa fa-search"></i> Search
				<% end %>
	    	</div>
	    </div>
	</div>
</div>
<% end %>

app/views/contacts/edit.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h2>Editing a contact</h2>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', contacts_path, {:style=>'color:#FFFFFF;', :class => "pull-right"} %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center"><h1><b>OVPD Contacts Database</b></h1></div>

<%= render 'search' %>
<br>
<%= link_to '<i class="fa fa-plus"></i> New Contact'.html_safe, new_contact_path, {:style=>'color:#EBECB0;', :class => "pull-right"} %>

<hr>
<%= render 'results' %>
<hr>

app/views/contacts/new.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h2>Create a new contact</h2>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', contacts_path, {:style=>'color:#FFFFFF;', :class => "pull-right"} %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact name:</strong>
  <%= @contact.contact_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @contact.position %>
</p>

<p>
  <strong>Affiliation:</strong>
  <%= @contact.affiliation %>
</p>

<p>
  <strong>Context:</strong>
  <%= @contact.context %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @contact.mobile %>
</p>

<p>
  <strong>Landline:</strong>
  <%= @contact.landline %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @contact.fax %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OVPD Contacts Database System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %></head>
<body>
	<div class="container-fluid"><!-- container -->
		<div class="row"> <!-- row -->
			<div class="col-xs-2">
			</div>
			<div class="col-xs-8">
				<%= yield %>
			</div>
			<div class="col-xs-2">
			</div>
		</div>
	</div>
</body>
</html>